source 'https://rubygems.org'

#gem 'jekyll'
gem "jekyll-gist"
gem 'jekyll-paginate'
gem "jekyll-asciidoc"
gem 'jekyll-twitter-plugin'
gem "github-pages", group: :jekyll_plugins

gem 'asciidoctor', '~> 1.5.4'
gem 'coderay', '1.1.1'

